package com.githubupload.mt

import android.content.ContentResolver
import android.net.Uri
import android.provider.DocumentsContract
import android.util.Base64
import org.json.JSONArray
import org.json.JSONObject
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.FileInputStream
import java.io.InputStream
import java.net.HttpURLConnection
import java.net.URL
import java.net.URLEncoder
import java.nio.charset.StandardCharsets
import java.time.Instant
import java.util.concurrent.Callable
import java.util.concurrent.Executors
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicInteger
import java.util.concurrent.atomic.AtomicLong

/** Uploads a local directory to a GitHub repository using GitHub's REST Git Database API. */
class GitUploader(
    private val contentResolver: ContentResolver,
    private val log: (String) -> Unit
) {
    data class Request(
        val source: Source,
        val repoUrl: String,
        val username: String,
        val token: String,
        val branch: String,
        val forcePush: Boolean
    )

    sealed class Source {
        data class FileSystem(val directory: File) : Source()
        data class TreeUri(val uri: Uri) : Source()
    }

    data class Result(
        val success: Boolean,
        val copiedFiles: Int,
        val copiedBytes: Long,
        val message: String
    )

    private data class RepoInfo(val owner: String, val repo: String)

    private data class LocalFile(
        val path: String,
        val streamFactory: () -> InputStream,
        val size: Long?
    )

    private data class BlobEntry(val path: String, val sha: String)

    fun upload(request: Request): Result {
        var copiedFiles = 0
        var copiedBytes = 0L
        try {
            validate(request)
            val repo = parseRepoUrl(request.repoUrl)
            val api = GitHubApi(repo, request.token)

            log("验证 GitHub 仓库：${repo.owner}/${repo.repo}")
            val repoJson = api.get("/repos/${repo.owner}/${repo.repo}")
            val defaultBranch = repoJson.optString("default_branch").trim().ifBlank { null }

            log("检查远程分支：${request.branch}")
            val targetRefPath = "/repos/${repo.owner}/${repo.repo}/git/ref/heads/${encodeSegment(request.branch)}"
            val existingRef = api.getOptional(targetRefPath)
            var parentSha: String? = null
            var baseTreeSha: String? = null

            if (existingRef != null) {
                parentSha = existingRef.getJSONObject("object").getString("sha")
                log("目标分支已存在，HEAD：${shortSha(parentSha)}")
                val commit = api.get("/repos/${repo.owner}/${repo.repo}/git/commits/${encodeSegment(parentSha)}")
                baseTreeSha = commit.getJSONObject("tree").getString("sha")
            } else if (!defaultBranch.isNullOrBlank()) {
                val defaultRef = api.getOptional(
                    "/repos/${repo.owner}/${repo.repo}/git/ref/heads/${encodeSegment(defaultBranch)}"
                )
                if (defaultRef != null) {
                    parentSha = defaultRef.getJSONObject("object").getString("sha")
                    val commit = api.get("/repos/${repo.owner}/${repo.repo}/git/commits/${encodeSegment(parentSha)}")
                    baseTreeSha = commit.getJSONObject("tree").getString("sha")
                    log("目标分支不存在，将基于默认分支 $defaultBranch 创建")
                }
            }

            val files = collectFiles(request.source)
            if (files.isEmpty()) {
                log("本地目录为空，自动创建 .gitkeep")
                val keep = "# generated by GitHub Upload Tool\n".toByteArray(StandardCharsets.UTF_8)
                val blobSha = api.createBlob(Base64.encodeToString(keep, Base64.NO_WRAP))
                val treeEntries = JSONArray().put(treeEntry(".gitkeep", blobSha))
                val treeSha = api.createTree(treeEntries, baseTreeSha)
                val commitMessage = "Auto upload by GitHub Upload Tool ${Instant.now()}"
                val commitSha = api.createCommit(commitMessage, treeSha, parentSha, request.username)
                updateOrCreateRef(api, request, existingRef, commitSha)
                copiedFiles = 1
                copiedBytes = keep.size.toLong()
                log("上传完成，远程提交：${shortSha(commitSha)}")
                return Result(true, copiedFiles, copiedBytes, "上传成功")
            }

            log("共发现 ${files.size} 个文件，开始并行创建 Blob（并发 $BLOB_CONCURRENCY）…")
            val (blobEntries, totalBytes) = createBlobsInParallel(api, files)
            copiedFiles = blobEntries.size
            copiedBytes = totalBytes
            log("全部 Blob 创建完成：${blobEntries.size} 个，${formatBytes(copiedBytes)}")

            // 分批次提交，避免单次 Tree 过大触发 GitHub 限制
            val batches = blobEntries.chunked(MAX_TREE_ENTRIES)
            log("将按 ${batches.size} 个批次上传（每批最多 $MAX_TREE_ENTRIES 个文件）")

            var currentParent = parentSha
            var currentBaseTree = baseTreeSha
            var lastCommitSha: String? = null

            for ((index, batch) in batches.withIndex()) {
                val batchNo = index + 1
                log("处理第 $batchNo/${batches.size} 批，共 ${batch.size} 个文件…")
                val treeEntries = JSONArray()
                for (entry in batch) {
                    treeEntries.put(treeEntry(entry.path, entry.sha))
                }
                val treeSha = api.createTree(treeEntries, currentBaseTree)
                val commitMessage = if (batches.size == 1) {
                    "Auto upload by GitHub Upload Tool ${Instant.now()}"
                } else {
                    "Auto upload by GitHub Upload Tool (batch $batchNo/${batches.size}) ${Instant.now()}"
                }
                val commitSha = api.createCommit(commitMessage, treeSha, currentParent, request.username)
                lastCommitSha = commitSha
                currentParent = commitSha
                // 下一批以当前 commit 的 tree 为 base，实现增量叠加
                val commitJson = api.get("/repos/${repo.owner}/${repo.repo}/git/commits/${encodeSegment(commitSha)}")
                currentBaseTree = commitJson.getJSONObject("tree").getString("sha")
                log("第 $batchNo 批提交完成：${shortSha(commitSha)}")
            }

            val finalSha = lastCommitSha!!
            updateOrCreateRef(api, request, existingRef, finalSha)
            log("上传完成，远程提交：${shortSha(finalSha)}")
            return Result(true, copiedFiles, copiedBytes, "上传成功（${batches.size} 批次）")
        } catch (e: Exception) {
            val message = buildErrorMessage(e)
            log("上传失败：$message")
            return Result(false, copiedFiles, copiedBytes, message)
        }
    }

    private fun updateOrCreateRef(
        api: GitHubApi,
        request: Request,
        existingRef: JSONObject?,
        commitSha: String
    ) {
        if (existingRef == null) {
            log("创建远程分支：${request.branch}")
            api.createRef(request.branch, commitSha)
        } else {
            if (request.forcePush) {
                log("⚠️ 使用 force=true 更新远程分支")
            }
            log("更新远程分支：${request.branch}")
            api.updateRef(request.branch, commitSha, request.forcePush)
        }
    }

    private fun createBlobsInParallel(api: GitHubApi, files: List<LocalFile>): Pair<List<BlobEntry>, Long> {
        val pool = Executors.newFixedThreadPool(BLOB_CONCURRENCY)
        val doneCount = AtomicInteger(0)
        val totalBytes = AtomicLong(0L)
        val total = files.size
        try {
            val futures = files.map { file ->
                pool.submit(Callable {
                    val bytes = readAllWithLimit(file.streamFactory, file.size)
                    val sha = api.createBlob(Base64.encodeToString(bytes, Base64.NO_WRAP))
                    val finished = doneCount.incrementAndGet()
                    totalBytes.addAndGet(bytes.size.toLong())
                    if (finished == 1 || finished % 10 == 0 || finished == total) {
                        log("已创建 Blob $finished/$total，${formatBytes(totalBytes.get())}")
                    }
                    BlobEntry(file.path, sha)
                })
            }
            val entries = futures.map { it.get(BLOB_TIMEOUT_MINUTES, TimeUnit.MINUTES) }
            return entries to totalBytes.get()
        } finally {
            pool.shutdownNow()
        }
    }

    private fun validate(request: Request) {
        require(request.username.isNotBlank()) { "Git 用户名不能为空" }
        require(request.token.isNotBlank()) { "Git 令牌不能为空" }
        require(isValidBranch(request.branch)) { "远程分支名无效：${request.branch}" }
        parseRepoUrl(request.repoUrl)
        when (val source = request.source) {
            is Source.FileSystem -> require(source.directory.isDirectory) {
                "本地目录不存在或不是目录：${source.directory.absolutePath}"
            }
            is Source.TreeUri -> require(DocumentsContract.isTreeUri(source.uri)) { "所选目录 URI 无效" }
        }
    }

    private fun parseRepoUrl(value: String): RepoInfo {
        val uri = runCatching { Uri.parse(value.trim()) }.getOrElse {
            throw IllegalArgumentException("远程仓库 URL 无效")
        }
        require(uri.scheme.equals("https", true)) { "远程仓库必须使用 HTTPS URL" }
        require(uri.host.equals("github.com", true)) { "当前版本仅支持 github.com 仓库" }
        val segments = uri.pathSegments.filter { it.isNotBlank() }
        require(segments.size >= 2) { "GitHub 仓库 URL 必须类似 https://github.com/用户名/仓库名.git" }
        val owner = segments[0]
        val repo = segments[1].removeSuffix(".git")
        require(owner.isNotBlank() && repo.isNotBlank()) { "GitHub 仓库 URL 无效" }
        return RepoInfo(owner, repo)
    }

    private fun isValidBranch(branch: String): Boolean {
        if (branch.isBlank() || branch.startsWith("/") || branch.endsWith("/") || branch.contains("..")) return false
        if (branch.contains("//") || branch.contains("\\") || branch.contains(" ")) return false
        if (branch.startsWith(".") || branch.endsWith(".") || branch.startsWith("-") || branch.endsWith(".lock")) return false
        if (branch.contains("@{")) return false
        return !branch.contains(Regex("[~^:?*\\[\\]\\u0000]"))
    }

    private fun collectFiles(source: Source): List<LocalFile> {
        val result = ArrayList<LocalFile>()
        when (source) {
            is Source.FileSystem -> collectFileSystem(source.directory, "", result)
            is Source.TreeUri -> {
                val rootId = DocumentsContract.getTreeDocumentId(source.uri)
                collectTreeChildren(source.uri, rootId, "", result)
            }
        }
        result.sortBy { it.path.lowercase() }
        return result
    }

    private fun collectFileSystem(directory: File, relative: String, out: MutableList<LocalFile>) {
        val children = directory.listFiles()?.sortedBy { it.name.lowercase() }
            ?: throw IllegalStateException("无法读取目录：${directory.absolutePath}")
        var visible = 0
        for (child in children) {
            if (child.name == ".git") {
                log("跳过 Git 元数据：${child.absolutePath}")
                continue
            }
            visible++
            val path = joinPath(relative, child.name)
            if (child.isDirectory) {
                val before = out.size
                collectFileSystem(child, path, out)
                if (out.size == before) out += gitKeepEntry(path)
            } else if (child.isFile) {
                out += LocalFile(path, { FileInputStream(child) }, child.length())
            }
        }
        if (visible == 0 && relative.isNotBlank()) out += gitKeepEntry(relative)
    }

    private fun collectTreeChildren(
        treeUri: Uri,
        parentDocumentId: String,
        relative: String,
        out: MutableList<LocalFile>
    ) {
        val childrenUri = DocumentsContract.buildChildDocumentsUriUsingTree(treeUri, parentDocumentId)
        val projection = arrayOf(
            DocumentsContract.Document.COLUMN_DOCUMENT_ID,
            DocumentsContract.Document.COLUMN_DISPLAY_NAME,
            DocumentsContract.Document.COLUMN_MIME_TYPE,
            DocumentsContract.Document.COLUMN_SIZE
        )
        contentResolver.query(childrenUri, projection, null, null, null)?.use { cursor ->
            val idIndex = cursor.getColumnIndex(DocumentsContract.Document.COLUMN_DOCUMENT_ID)
            val nameIndex = cursor.getColumnIndex(DocumentsContract.Document.COLUMN_DISPLAY_NAME)
            val mimeIndex = cursor.getColumnIndex(DocumentsContract.Document.COLUMN_MIME_TYPE)
            val sizeIndex = cursor.getColumnIndex(DocumentsContract.Document.COLUMN_SIZE)
            require(idIndex >= 0 && nameIndex >= 0 && mimeIndex >= 0) { "文件提供商返回的数据不完整" }

            while (cursor.moveToNext()) {
                val id = cursor.getString(idIndex)
                val name = cursor.getString(nameIndex).orEmpty()
                if (name.isBlank()) continue
                if (name == ".git") {
                    log("跳过 Git 元数据目录")
                    continue
                }
                val path = joinPath(relative, name)
                val mime = cursor.getString(mimeIndex).orEmpty()
                if (mime == DocumentsContract.Document.MIME_TYPE_DIR) {
                    val before = out.size
                    collectTreeChildren(treeUri, id, path, out)
                    if (out.size == before) out += gitKeepEntry(path)
                } else {
                    val documentUri = DocumentsContract.buildDocumentUriUsingTree(treeUri, id)
                    val size = if (sizeIndex >= 0 && !cursor.isNull(sizeIndex)) cursor.getLong(sizeIndex) else null
                    out += LocalFile(
                        path,
                        { contentResolver.openInputStream(documentUri) ?: throw IllegalStateException("无法打开文件：$path") },
                        size
                    )
                }
            }
        } ?: throw IllegalStateException("无法读取目录内容")
    }

    private fun gitKeepEntry(directoryPath: String): LocalFile {
        val bytes = "# generated by GitHub Upload Tool\n".toByteArray(StandardCharsets.UTF_8)
        return LocalFile(joinPath(directoryPath, ".gitkeep"), { bytes.inputStream() }, bytes.size.toLong())
    }

    private fun readAllWithLimit(factory: () -> InputStream, expectedSize: Long?): ByteArray {
        if (expectedSize != null && expectedSize > MAX_FILE_BYTES) {
            throw IllegalStateException("单个文件超过 ${formatBytes(MAX_FILE_BYTES)}，无法通过当前版本上传")
        }
        val initial = if (expectedSize != null && expectedSize in 1..INITIAL_BUFFER_LIMIT) expectedSize.toInt() else 8192
        val output = ByteArrayOutputStream(initial)
        factory().use { input ->
            val buffer = ByteArray(128 * 1024) // 更大缓冲提升读盘速度
            var total = 0L
            while (true) {
                val count = input.read(buffer)
                if (count < 0) break
                if (count == 0) continue
                total += count
                if (total > MAX_FILE_BYTES) throw IllegalStateException("单个文件超过 ${formatBytes(MAX_FILE_BYTES)}，无法通过当前版本上传")
                output.write(buffer, 0, count)
            }
        }
        return output.toByteArray()
    }

    private fun treeEntry(path: String, blobSha: String): JSONObject = JSONObject()
        .put("path", path)
        .put("mode", "100644")
        .put("type", "blob")
        .put("sha", blobSha)

    private fun joinPath(parent: String, child: String): String = if (parent.isBlank()) child else "$parent/$child"

    private fun buildErrorMessage(error: Throwable): String {
        val message = generateSequence(error) { it.cause }
            .mapNotNull { it.message?.trim() }
            .firstOrNull { it.isNotBlank() }
            ?: error.javaClass.simpleName
        return message.take(3000)
    }

    private fun shortSha(sha: String): String = sha.take(10)

    private fun formatBytes(bytes: Long): String = when {
        bytes < 1024L -> "$bytes B"
        bytes < 1024L * 1024L -> "%.1f KB".format(bytes / 1024.0)
        bytes < 1024L * 1024L * 1024L -> "%.1f MB".format(bytes / (1024.0 * 1024.0))
        else -> "%.2f GB".format(bytes / (1024.0 * 1024.0 * 1024.0))
    }

    private fun encodeSegment(value: String): String = URLEncoder.encode(value, "UTF-8").replace("+", "%20")

    private inner class GitHubApi(private val repo: RepoInfo, private val token: String) {
        fun get(path: String): JSONObject = request("GET", path, null, setOf(200))

        fun getOptional(path: String): JSONObject? = try {
            get(path)
        } catch (e: ApiException) {
            if (e.code == 404) null else throw e
        }

        fun createBlob(base64Content: String): String = request(
            "POST",
            "/repos/${repo.owner}/${repo.repo}/git/blobs",
            JSONObject().put("content", base64Content).put("encoding", "base64"),
            setOf(201)
        ).getString("sha")

        fun createTree(entries: JSONArray, baseTreeSha: String?): String {
            val body = JSONObject().put("tree", entries)
            if (!baseTreeSha.isNullOrBlank()) body.put("base_tree", baseTreeSha)
            return request(
                "POST",
                "/repos/${repo.owner}/${repo.repo}/git/trees",
                body,
                setOf(201)
            ).getString("sha")
        }

        fun createCommit(message: String, treeSha: String, parentSha: String?, username: String): String {
            val body = JSONObject()
                .put("message", message)
                .put("tree", treeSha)
                .put("author", JSONObject().put("name", username).put("email", "$username@users.noreply.github.com"))
                .put("committer", JSONObject().put("name", username).put("email", "$username@users.noreply.github.com"))
            if (!parentSha.isNullOrBlank()) body.put("parents", JSONArray().put(parentSha))
            return request("POST", "/repos/${repo.owner}/${repo.repo}/git/commits", body, setOf(201)).getString("sha")
        }

        fun createRef(branch: String, commitSha: String) {
            request(
                "POST",
                "/repos/${repo.owner}/${repo.repo}/git/refs",
                JSONObject().put("ref", "refs/heads/$branch").put("sha", commitSha),
                setOf(201)
            )
        }

        fun updateRef(branch: String, commitSha: String, force: Boolean) {
            request(
                "PATCH",
                "/repos/${repo.owner}/${repo.repo}/git/refs/heads/${encodeSegment(branch)}",
                JSONObject().put("sha", commitSha).put("force", force),
                setOf(200)
            )
        }

        private fun request(method: String, path: String, body: JSONObject?, acceptable: Set<Int>): JSONObject {
            val connection = (URL("https://api.github.com$path").openConnection() as HttpURLConnection).apply {
                requestMethod = method
                connectTimeout = CONNECT_TIMEOUT_MS
                readTimeout = READ_TIMEOUT_MS
                doInput = true
                setRequestProperty("Accept", "application/vnd.github+json")
                setRequestProperty("Authorization", "Bearer $token")
                setRequestProperty("X-GitHub-Api-Version", "2022-11-28")
                setRequestProperty("User-Agent", "GitHubUploadTool-Android/3.1")
                if (body != null) {
                    doOutput = true
                    setRequestProperty("Content-Type", "application/json; charset=utf-8")
                }
            }
            try {
                if (body != null) {
                    val bytes = body.toString().toByteArray(StandardCharsets.UTF_8)
                    connection.outputStream.use { it.write(bytes) }
                }
                val code = connection.responseCode
                val responseText = (if (code in 200..399) connection.inputStream else connection.errorStream)
                    ?.bufferedReader(StandardCharsets.UTF_8).use { it?.readText().orEmpty() }
                if (code !in acceptable) {
                    val message = runCatching { JSONObject(responseText).optString("message") }.getOrNull()
                    throw ApiException(code, message?.ifBlank { responseText } ?: responseText)
                }
                return if (responseText.isBlank()) JSONObject() else JSONObject(responseText)
            } finally {
                connection.disconnect()
            }
        }
    }

    private class ApiException(val code: Int, message: String) : RuntimeException("GitHub API $code：$message")

    companion object {
        private const val MAX_FILE_BYTES = 80L * 1024L * 1024L
        private const val INITIAL_BUFFER_LIMIT = 4L * 1024L * 1024L
        private const val CONNECT_TIMEOUT_MS = 20_000
        private const val READ_TIMEOUT_MS = 180_000
        /** 单次 createTree 的最大条目数，超过则自动分批次多次提交 */
        private const val MAX_TREE_ENTRIES = 150
        /** 并行创建 Blob 的线程数，兼顾速度与 GitHub 次要速率限制 */
        private const val BLOB_CONCURRENCY = 6
        private const val BLOB_TIMEOUT_MINUTES = 30L
    }
}
